### ISSUE TITLE
0508.2 has extension “.krnl”

### ISSUE THREAD

**Issue by mscuthbert** [Gaspar-Online-Edition/Gaspar-Online-Edition#4]
Not sure if this is intentional because of the .2 or not.

**Comment by craigsapp** [comment]
Thanks: No, that is a typo.  The .2 means that it is a variant of the file without the .2.

Fixed with commit https://github.com/Gaspar-Online-Edition/Gaspar-Online-Edition/commit/c390f7264f20fd76f778391252108d93b4179de1
